#Use matrix to speed up the build process
strategy:
  matrix:
    TARGET_ARMPKG:
      Build.Pkgs: 'ArmPkg'
    TARGET_ARMPLATFORMPKG:
      Build.Pkgs: 'ArmPlatformPkg'

variables:
  GCC_AARCH_PREFIX: bin/aarch64-linux-gnu-
  GCC_ARM_PREFIX: bin/arm-linux-gnueabihf-

workspace:
  clean: all

steps:
- checkout: self
  clean: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7.x'
    architecture: 'x64'

- script: pip3 install -r requirements.txt --upgrade
  displayName: 'Install/Upgrade pip modules'

#Build repo
- task: CmdLine@1
  displayName: Setup $(Build.Pkgs)
  inputs:
    filename: stuart_setup
    arguments: -c CISettings.py -p $(Build.Pkgs)

- task: CmdLine@1
  displayName: Setup $(Build.Pkgs)
  inputs:
    filename: stuart_ci_setup
    arguments: -c CISettings.py --force-git -p $(Build.Pkgs)

- task: CmdLine@1
  displayName: Update $(Build.Pkgs)
  inputs:
    filename: stuart_update
    arguments: -c CISettings.py --Tool_Chain GCC5 -p $(Build.Pkgs)

- task: CmdLine@1
  displayName: Build and Test $(Build.Pkgs)
  inputs:
    filename: stuart_ci_build
    arguments: -c CISettings.py --Tool_Chain GCC5 -p $(Build.Pkgs)

# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  displayName: 'Publish junit test results'
  continueOnError: true
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: 'Build/TestSuites.xml'
    testRunTitle: "ArmSilicon"
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    mergeTestResults: true # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    publishRunAttachments: true # Optional

# Copy the build logs to the artifact staging directory
- task: CopyFiles@2
  displayName: "Copy build logs"
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    contents: |
      Build/**/BUILDLOG_*.txt
      Build/**/BUILDLOG_*.md
      Build/**/CI_*.txt
      Build/**/CI_*.md
      Build/**/CISETUP.txt
      Build/**/SETUPLOG.txt
      Build/**/UPDATELOG.txt
      Build/**/TestSuites.xml
      Build/**/BUILD_TOOLS_REPORT.html
      Build/**/OVERRIDELOG.txt
    flattenFolders: true

# Publish build artifacts to Azure Artifacts/TFS or a file share
- task: PublishBuildArtifacts@1
  continueOnError: true
  displayName: "Publish build logs"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Build Logs $(Build.Pkgs)'